apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mar15-3-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/mar15-3/overlays/prod
    repoURL: https://github.com/redhat-appstudio-mjf/mar15-3-gitops.git
    targetRevision: main
  destination:
    namespace: pvt-1-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
