apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mar15-3 
  janus-idp.io/tekton: mar15-3
  backstage.io/kubernetes-id: mar15-3
  backstage.io/kubernetes-namespace: pvt-1 
  app.kubernetes.io/part-of: mar15-3
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  